apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: backend-api
  ports:
    - port: {{ .Values.backendApi.service.port }}
      targetPort: {{ .Values.backendApi.service.targetPort }}
